title: RECON-TERRASSA ![](https://github.com/gdsa-upc/Recon-Terrassa/blob/gh-pages/images/logo_amb_black.png)
description: cercador visual d'imatges
google_analytics: ![](https://github.com/gdsa-upc/Recon-Terrassa/blob/gh-pages/images/map.png)
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
  ![](https://github.com/gdsa-upc/Recon-Terrassa/blob/gh-pages/images/map.png)
